### ISSUE TITLE
Use the `atom-text-editor` tag instead of the `colors` class.

### ISSUE THREAD

**Issue by 21xhipster** [jesseweed/seti-syntax#40] opened 2015-02-12 01:16 UTC
In index.less: Use the `atom-text-editor` tag instead of the `editor`, `editor-colors` class.

**Comment by jesseweed** [comment] 2015-02-15 07:41
This is a duplicate of #38 which has been fixed in v0.3.2.

**Closed by jesseweed** 2015-02-15 07:41 UTC
Labels: duplicate
