### ISSUE TITLE
My index cursor is 1 digit after the text

### ISSUE THREAD

**Issue by opexa** [jesseweed/seti-syntax#109] opened 2015-10-31 15:12 UTC
My index/blinking cursor in the text editor is broken.Its actually 1 digit after thing I've selected.How to fix it

**Comment by dab00** [comment] 2015-10-31 17:17
Same here

**Comment by opexa** [comment] 2015-10-31 20:28
GOD DAMN THANK YOU!GOD BLESS YA!

**Comment by msyrus** [comment] 2015-11-01 04:54
The problem is due to introducing "Enable Shadow DOM" in Atom 1.1

**Comment by opexa** [comment] 2015-11-01 09:19
Whats this "Shadow DOM"

**Comment by jesseweed** [comment] 2015-11-01 22:08
This is fixed in 0.4.1 which is published to apm now.

**Closed by jesseweed** 2015-11-01 22:08 UTC
