### ISSUE TITLE
ThemePackage.getStylesheetsPath is deprecated.

### ISSUE THREAD

**Issue by Zynesteri** [jesseweed/seti-syntax#77] opened 2015-04-08 08:03 UTC
Store package style sheets in the `styles/` directory instead of `stylesheets/` in the `seti-syntax` package
```
ThemePackage.getStylesheetsPath (C:\Users\Admin\AppData\Local\atom\app-0.190.0\resources\app\src\package.js:433:9)
<unknown> (C:\Users\Admin\AppData\Local\atom\app-0.190.0\resources\app\src\theme-manager.js:434:35)
```

**Comment by asantos3** [comment] 2015-04-08 13:58
Duplicate of #67.

**Closed** 2015-04-24 23:07 UTC
Labels: duplicate
