### ISSUE TITLE
ThemePackage.getStylesheetsPath is deprecated.

### ISSUE THREAD

**Issue by zetay** [jesseweed/seti-syntax#91] opened 2015-04-23 01:24 UTC
Store package style sheets in the `styles/` directory instead of `stylesheets/` in the `seti-syntax` package
```
ThemePackage.getStylesheetsPath (D:\GreenSoft\Atom\resources\app\src\package.js:430:9)
ThemePackage.getStylesheetPaths (D:\GreenSoft\Atom\resources\app\src\package.js:441:32)
```

**Comment by asantos3** [comment] 2015-04-23 18:51
Duplicate of #67, please close this.

**Closed** 2015-04-24 23:07 UTC
Labels: duplicate
