### ISSUE TITLE
ThemePackage.getStylesheetsPath is deprecated.

### ISSUE THREAD

**Issue by steelx** [jesseweed/seti-syntax#78] opened 2015-04-09 10:10 UTC
Store package style sheets in the `styles/` directory instead of `stylesheets/` in the `seti-syntax` package
```
ThemePackage.getStylesheetsPath (C:\Users\aborad\AppData\Local\atom\app-0.190.0\resources\app\src\package.js:433:9)
ThemePackage.getStylesheetPaths (C:\Users\aborad\AppData\Local\atom\app-0.190.0\resources\app\src\package.js:444:32)
```

**Comment by asantos3** [comment] 2015-04-09 10:23
C'mon @jesseweed, fix this now. Duplicate of #67.

**Closed** 2015-04-24 23:07 UTC
Labels: duplicate
