### ISSUE TITLE
ThemePackage.getStylesheetsPath is deprecated.

### ISSUE THREAD

**Issue by mychriz** [jesseweed/seti-syntax#86] opened 2015-04-17 11:51 UTC
Store package style sheets in the `styles/` directory instead of `stylesheets/` in the `seti-syntax` package
```
ThemePackage.getStylesheetsPath (/Applications/Atom.app/Contents/Resources/app/src/package.js:430:9)
<unknown> (/Applications/Atom.app/Contents/Resources/app/src/theme-manager.js:434:35)
```

Same question. I don´t know who to fix it.

**Comment by asantos3** [comment] 2015-04-17 13:10
Duplicate of #67, please close this.

**Closed** 2015-04-17 16:08 UTC
