### ISSUE TITLE
Mmmm errors everywhere

### ISSUE THREAD

**Issue by CavariuX** [jesseweed/seti-syntax#39] opened 2015-02-12 00:54 UTC
In index.less: Use the selector `atom-text-editor[mini]` to select mini-editors.
In index.less: Use the `atom-text-editor` tag instead of the `editor` class.
In index.less: Use the `atom-text-editor` tag instead of the `editor-colors` class.

**Comment by jesseweed** [comment] 2015-02-15 07:39
This is a duplicate of #38 which has been fixed in v0.3.2.

**Closed by jesseweed** 2015-02-15 07:39 UTC
