### ISSUE TITLE
ThemePackage.getStylesheetsPath is deprecated.

### ISSUE THREAD

**Issue by stychu** [jesseweed/seti-syntax#87] opened 2015-04-18 21:07 UTC
Store package style sheets in the `styles/` directory instead of `stylesheets/` in the `seti-syntax` package
```
ThemePackage.getStylesheetsPath (C:\Users\Ja\AppData\Local\atom\app-0.192.0\resources\app\src\package.js:430:9)
ThemePackage.getStylesheetPaths (C:\Users\Ja\AppData\Local\atom\app-0.192.0\resources\app\src\package.js:441:32)
```

Also

Store package style sheets in the `styles/` directory instead of `stylesheets/` in the `seti-syntax` package
```
ThemePackage.getStylesheetsPath (C:\Users\Ja\AppData\Local\atom\app-0.192.0\resources\app\src\package.js:430:9)
<unknown> (C:\Users\Ja\AppData\Local\atom\app-0.192.0\resources\app\src\theme-manager.js:434:35)
```

**Comment by asantos3** [comment] 2015-04-18 23:44
Duplicate of #67, please close this.

**Comment by stychu** [comment] 2015-04-19 09:00
Hmm ok Im pretty new to the github and atom etc. so dont know how to fix this issue. Any tip please ?

**Comment by asantos3** [comment] 2015-04-19 09:15
Just close it, this bug/issue has been reported in another issue so there's no need to duplicate it.

**Closed** 2015-04-19 09:39 UTC
