### ISSUE TITLE
ThemePackage.getStylesheetsPath is deprecated.

### ISSUE THREAD

**Issue by post72** [jesseweed/seti-syntax#83] opened 2015-04-15 21:23 UTC
Store package style sheets in the `styles/` directory instead of `stylesheets/` in the `seti-syntax` package
```
ThemePackage.getStylesheetsPath (C:\Users\bburch\AppData\Local\atom\app-0.190.0\resources\app\src\package.js:433:9)
ThemePackage.getStylesheetPaths (C:\Users\bburch\AppData\Local\atom\app-0.190.0\resources\app\src\package.js:444:32)
```

**Comment by post72** [comment] 2015-04-15 21:24
Issue found in Atom v0.190 running on Windows 8.1 OS

**Comment by asantos3** [comment] 2015-04-16 09:16
Duplicate of #67, please close this.

**Closed** 2015-04-16 14:07 UTC
