### ISSUE TITLE
ThemePackage.getStylesheetsPath is deprecated.

### ISSUE THREAD

**Issue by FlashxGamer** [jesseweed/seti-syntax#69] opened 2015-04-05 06:53 UTC
Store package style sheets in the `styles/` directory instead of `stylesheets/` in the `seti-syntax` package
```
ThemePackage.getStylesheetsPath (C:\Users\Sigma\AppData\Local\atom\app-0.189.0\resources\app\src\package.js:448:9)
<unknown> (C:\Users\Sigma\AppData\Local\atom\app-0.189.0\resources\app\src\theme-manager.js:492:35)
```

**Comment by designsimply** [comment] 2015-04-05 18:06
Duplicate of #68

**Comment by asantos3** [comment] 2015-04-06 16:34
Duplicate of #67.

**Comment by designsimply** [comment] 2015-04-06 16:50
Thanks asantos3! I missed the PR before. :)

**Closed** 2015-04-24 23:07 UTC
Labels: duplicate
