### ISSUE TITLE
Cursor off

### ISSUE THREAD

**Issue by xenspidey** [jesseweed/seti-syntax#108] opened 2015-10-30 16:08 UTC
The cursor position is not lining up with text. Switching syntax themes fixes it so it must be theme related

**Comment by thewalkingtoast** [comment] 2015-10-30 16:16
Duplicate of #106.

**Comment by derekclair** [comment] 2015-10-31 00:04
I don't think it's a duplicate, cause the proposed solution in #106 isn't solving it for me... The cursor matches the selector but it's still way off....

**Comment by Arcanemagus** [comment] 2015-10-31 00:07
@derekclair did you restart Atom after making the fix? The solution in #106 is definitely the fix to this issue...

**Comment by derekclair** [comment] 2015-10-31 00:11
And... we're back in business. Thank you @Arcanemagus!

**Comment by Arcanemagus** [comment] 2015-10-31 05:20
Good to hear :wink:.

**Comment by jesseweed** [comment] 2015-11-01 22:11
This is fixed in 0.4.1 which was just published to apm.

**Closed by jesseweed** 2015-11-01 22:11 UTC
