### ISSUE TITLE
ThemePackage.getStylesheetsPath is deprecated.

### ISSUE THREAD

**Issue by Kunamatata** [jesseweed/seti-syntax#80] opened 2015-04-09 15:02 UTC
Store package style sheets in the `styles/` directory instead of `stylesheets/` in the `seti-syntax` package
```
ThemePackage.getStylesheetsPath (C:\Users\max.caly\AppData\Local\atom\app-0.190.0\resources\app\src\package.js:433:9)
<unknown> (C:\Users\max.caly\AppData\Local\atom\app-0.190.0\resources\app\src\theme-manager.js:434:35)
```

**Comment by asantos3** [comment] 2015-04-09 18:31
Duplicate of #67, please close this.

**Closed** 2015-04-24 23:07 UTC
Labels: duplicate
