### ISSUE TITLE
Package.getStylesheetsPath is deprecated.

### ISSUE THREAD

**Issue by nykolla** [jesseweed/seti-syntax#70] opened 2015-04-06 09:48 UTC
Store package style sheets in the `styles/` directory instead of `stylesheets/` in the `auto-indent` package
```
ThemePackage.getStylesheetsPath (C:\Users\nikola\AppData\Local\atom\app-0.189.0\resources\app\src\package.js:448:9)
<unknown> (C:\Users\nikola\AppData\Local\atom\app-0.189.0\resources\app\src\theme-manager.js:492:35)
```

**Comment by asantos3** [comment] 2015-04-06 16:34
Duplicate of #67.

**Closed** 2015-04-24 23:07 UTC
Labels: duplicate
