### ISSUE TITLE
ThemePackage.getStylesheetsPath is deprecated.

### ISSUE THREAD

**Issue by evangelicodenis12** [jesseweed/seti-syntax#89] opened 2015-04-19 05:12 UTC
Store package style sheets in the `styles/` directory instead of `stylesheets/` in the `seti-syntax` package
```
ThemePackage.getStylesheetsPath (C:\Users\denis_000\AppData\Local\atom\app-0.192.0\resources\app\src\package.js:430:9)
ThemePackage.getStylesheetPaths (C:\Users\denis_000\AppData\Local\atom\app-0.192.0\resources\app\src\package.js:441:32)


```

**Comment by asantos3** [comment] 2015-04-19 09:19
Duplicate of #67, please close this.

**Closed** 2015-04-24 23:07 UTC
Labels: duplicate
