### ISSUE TITLE
ThemePackage.getStylesheetsPath is deprecated.

### ISSUE THREAD

**Issue by nullv01d** [jesseweed/seti-syntax#73] opened 2015-04-06 16:51 UTC
Store package style sheets in the `styles/` directory instead of `stylesheets/` in the `seti-syntax` package
```
ThemePackage.getStylesheetsPath (C:\Users\adora\AppData\Local\atom\app-0.189.0\resources\app\src\package.js:448:9)
ThemePackage.getStylesheetPaths (C:\Users\adora\AppData\Local\atom\app-0.189.0\resources\app\src\package.js:459:32)
```

**Comment by asantos3** [comment] 2015-04-06 16:57
Duplicate of #67.

**Closed** 2015-04-24 23:07 UTC
Labels: duplicate
